### ISSUE TITLE
Old notification leads to Internal Error

### ISSUE THREAD

**Issue by luke-** [humhub/reportcontent#72]
Steps to reproduce:

- User reports a content
- Admin clicks on the Notification
- and Deletes the user with all content
- Admin clicks again on the Notification
- Internal Error 

```
yii\base\ErrorException: Trying to get property 'content_id' of non-object in /srv/www/htdocs/community/modules/reportcontent/notifications/NewReportAdmin.php:94
Stack trace:
#0 /srv/www/htdocs/community/modules/reportcontent/notifications/NewReportAdmin.php(94): yii\base\ErrorHandler->handleError()
#1 /srv/www/htdocs/community/modules/reportcontent/notifications/NewReportAdmin.php(63): humhub\modules\reportcontent\notifications\NewReportAdmin->getReportedRecord()
#2 /srv/humhub/protected/humhub/modules/notification/controllers/EntryController.php(61): humhub\modules\reportcontent\notifications\NewReportAdmin->getUrl()
#3 [internal function]: humhub\modules\notification\controllers\EntryController->actionIndex()
#4 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#6 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#7 /srv/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#8 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#9 /srv/www/htdocs/community/index.php(24): yii\base\Application->run()
#10 {main}
```

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/reportcontent/pull/73.

I have investigated that on deleting of user the records are deleted from tables `content` and `report_content` but not deleted from the table `notification` because there is no foreign key (there are two columns `source_class` + `source_pk`).
But old notification records can be deleted either by cron job or Integrity Check command, so I think no need to do any fixes in core side.

**Comment by luke-** [comment]
@yurabakhtin What with this event? I would expect this would remove related Notifications?
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/notification/Events.php#L171-L177

**Comment by yurabakhtin** [comment]
@luke- I think on user deleting the Active Record `ReportContent` is deleted from DB because it is linked with column `content_id` by foreign key, i.e. the `ReportContent` is deleted when `Content` record is deleted from DB.
The event `onActiveRecordDelete` is called only when we run `ReportContent->delete()` from PHP side, but it is not called when the record is deleted from DB side(when it is deleted by foreign key on cascade way).

**Comment by luke-** [comment]
@yurabakhtin I would prefer mainly do a cleanup of the database via events and not via FKs. Additional FKs are good, but we shouldn't rely on it. 

So wouldn't it be a solution to delete the content reports during user delete events?

**Comment by yurabakhtin** [comment]
> So wouldn't it be a solution to delete the content reports during user delete events?

@luke- I have implemented a solution to delete all Report Content records on deleting of Content - see commit https://github.com/humhub/reportcontent/pull/73/commits/ebe7ce0aa7c1420099692f014fad04e88ba5a8f0.
This event will be triggered on user deleting because the core module `content` uses event `User::EVENT_BEFORE_DELETE`, so on deleting of User the method `Content->hardDelete()` is called and then new event `humhub\modules\reportcontent\Events::onContentBeforeDelete` will be called where we run `ReportContent::delete()`, and the `ReportContent` is `ActiveRecord` so all linked records like Notifications will be removed from db as well.
