### ISSUE TITLE
Clearing reported content

### ISSUE THREAD

**Issue by G-Burnett** [humhub/reportcontent#75]
Hi, once any reported post has been deleted, it doesn't seem to be possible to clear the list and remove the red flag against 'reported content' in the menu. Is this intended behaviour. Version 1.0.3

**Comment by G-Burnett** [comment]
Hi Luke,  do you know when this issue will be fixed?

**Comment by yurabakhtin** [comment]
@luke- I have tested it with a deleted post, and when I see the red flag then I also see the deleted post in the "Reported Content" list. I had only an error page with text "Oooops... It looks like you may have taken the wrong turn." on click the deleted post from the "Reported Content" list.
So I have decided to hide all not published contents from the "Reported Content" list and don't count such contents in the red flag, because deleted contents are removed from DB completely by queued cron job `humhub\modules\content\jobs\PurgeDeletedContents`.

Please note the column `content.state` has been added since v1.14 so I had to increase min version for this module as well.
PR https://github.com/humhub/reportcontent/pull/78.
